ifeq ($(BOARD_HAVE_SAMSUNG_WIFI),true)

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

ifdef WIFI_DRIVER_NVRAM_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_NVRAM_PATH=\"$(WIFI_DRIVER_NVRAM_PATH)\"
endif

ifdef WIFI_DRIVER_NVRAM_PATH_PARAM
LOCAL_CFLAGS += -DWIFI_DRIVER_NVRAM_PATH_PARAM=\"$(WIFI_DRIVER_NVRAM_PATH_PARAM)\"
endif

LOCAL_SRC_FILES := \
    macloader.c

LOCAL_SHARED_LIBRARIES := \
    liblog libutils

LOCAL_MODULE := macloader
LOCAL_MODULE_TAGS := optional

include $(BUILD_EXECUTABLE)

endif
